/**
 * Question 2: Pythagorean Triplets
 * 
 * Problem: Generate all Pythagorean triplets with values smaller than a given limit.
 * Input: limit = 20
 * Output:
 * 3  4  5
 * 8  6  10
 * 5  12 13
 * 15 8  17
 * 12 16 20
 * 
 * Beginner Friendly Solution Approach:
 * 1. A Pythagorean triplet satisfies a² + b² = c² where a, b, c are integers.
 * 2. This sequence in the sample output is generated by Euclid's formula.
 *    For beginner friendliness, we explain Euclid's formula simply: 
 *    a = m² - n², b = 2mn, c = m² + n², where m > n > 0.
 * 3. We start with m = 2, and loop n from 1 to m-1, calculating a, b, c, 
 *    until c exceeds the limit.
 */
import java.util.Scanner;

public class Qs2_PythagoreanTriplets {
    
    // Beginner readable method to generate triplets using Euclid's formula
    public static void generateTriplets(int limit) {
        int m = 2;
        int c = 0;
        
        // Loop while the smallest possible hypotenuse (with n=1) is <= limit
        while ((m * m) + 1 <= limit) {
            for (int n = 1; n < m; n++) {
                // Applying formula
                int a = (m * m) - (n * n);
                int b = 2 * m * n;
                c = (m * m) + (n * n);
                
                // If c is greater than limit, we stop checking further n values
                if (c > limit) {
                    break;
                }
                
                // Print the triplet
                System.out.printf("%d %d %d\n", a, b, c);
            }
            m++;
        }
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.print("Input: limit = ");
        if(scanner.hasNextInt()) {
            int limit = scanner.nextInt();
            System.out.println("Output:");
            generateTriplets(limit);
        } else {
            System.out.println("Please enter a valid integer limit.");
        }
        
        scanner.close();
    }
}

/* 
 * ==========================================
 * OPTIMIZED APPROACH AND CODE
 * ==========================================
 * Optimized Approach:
 * Generating Triplets using Euclid's formula is already highly optimized, running in 
 * O(sqrt(limit)) time. To further optimize mathematically, we could pre-calculate 
 * maximum bounds to loop instead of using a while-condition to avoid extra steps.
 * 
 * Optimized Code (Slight structural improvement):
 * 
 * public static void generateTripletsOptimized(int limit) {
 *     int maxM = (int) Math.sqrt(limit);
 *     for (int m = 2; m <= maxM; m++) {
 *         for (int n = 1; n < m; n++) {
 *             int c = m * m + n * n;
 *             if (c > limit) break;
 *             int a = m * m - n * n;
 *             int b = 2 * m * n;
 *             System.out.printf("%d %d %d\n", a, b, c);
 *         }
 *     }
 * }
 */
